sources:
  postgres-source:
    kind: postgres
    host: db
    port: 5432
    database: toolbox_db
    user: toolbox_user
    password: my-password

tools:
  document-search:
    kind: postgres-sql
    source: postgres-source
    description: "Performs a vector similarity search to find documents semantically similar to a given query."
    parameters:
      - name: embedding
        type: array
        description: "The embedding vector representing the user's query."
    statement: |
      SELECT id, content FROM documents ORDER BY embedding <-> $1 LIMIT 10;

  get-document-by-id:
    kind: postgres-sql
    source: postgres-source
    description: "Fetches a specific document by its unique ID."
    parameters:
      - name: id
        type: number
        description: "The unique ID of the document to retrieve."
    statement: |
      SELECT id, content FROM documents WHERE id = $1;

  get-all-documents:
    kind: postgres-sql
    source: postgres-source
    description: "Retrieves all documents. Use only if a vector search is not appropriate."
    statement: |
      SELECT id, content FROM documents;

  execute_sql_tool:
    kind: postgres-execute-sql
    source: postgres-source
    description: Use this tool to execute sql statement.

  list_active_queries:
    kind: postgres-list-active-queries
    source: postgres-source
    description: List the top N (default 50) currently running queries (state='active') from pg_stat_activity, ordered by longest-running first. Returns pid, user, database, application_name, client_addr, state, wait_event_type/wait_event, backend/xact/query start times, computed query_duration, and the SQL text.

  list_available_extensions:
    kind: postgres-list-available-extensions
    source: postgres-source
    description: Discover all PostgreSQL extensions available for installation on this server, returning name, default_version, and description.

  list_installed_extensions:
    kind: postgres-list-installed-extensions
    source: postgres-source
    description: List all installed PostgreSQL extensions with their name, version, schema, owner, and description.

  postgres_list_tables:
    kind: postgres-list-tables
    source: postgres-source
    description: Use this tool to retrieve schema information for all or specified tables. Output format can be simple (only table names) or detailed.

  wait_for_tool:
    kind: wait
    description: Use this tool to pause execution for a specified duration.
    timeout: 30s